package school.czm.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;
import school.czm.entity.Admin;
@Repository
public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Wed Dec 18 14:31:12 CST 2019
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Wed Dec 18 14:31:12 CST 2019
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Wed Dec 18 14:31:12 CST 2019
     */
    Admin selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Wed Dec 18 14:31:12 CST 2019
     */
    List<Admin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Wed Dec 18 14:31:12 CST 2019
     */
    int updateByPrimaryKey(Admin record);

    Admin selectByNameAndPwd(Admin admin);
}