package school.czm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import school.czm.entity.OrderItem;
@Repository
public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Thu Dec 19 16:01:57 CST 2019
     */
    int deleteByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Thu Dec 19 16:01:57 CST 2019
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Thu Dec 19 16:01:57 CST 2019
     */
    OrderItem selectByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Thu Dec 19 16:01:57 CST 2019
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Thu Dec 19 16:01:57 CST 2019
     */
    int updateByPrimaryKey(OrderItem record);

    List<OrderItem> getOrderItem(@Param("id")String id);
}