package school.czm.entity;

import java.util.Date;

public class Good {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_id
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_miaoshu
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private String goodsMiaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_pic
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.market_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Integer marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.mall_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Integer mallPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.catelog_id
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Catelog catelog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.stock_num
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Integer stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_address
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private String goodsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.enter_date
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    private Date enterDate;


    @Override
    public String toString() {
        return "Good{" +
                "goodsId=" + goodsId +
                ", goodsName='" + goodsName + '\'' +
                ", goodsMiaoshu='" + goodsMiaoshu + '\'' +
                ", goodsPic='" + goodsPic + '\'' +
                ", marketPrice=" + marketPrice +
                ", mallPrice=" + mallPrice +
                ", catelog=" + catelog +
                ", stockNum=" + stockNum +
                ", goodsAddress='" + goodsAddress + '\'' +
                ", enterDate=" + enterDate +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_miaoshu
     *
     * @return the value of t_goods.goods_miaoshu
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public String getGoodsMiaoshu() {
        return goodsMiaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_miaoshu
     *
     * @param goodsMiaoshu the value for t_goods.goods_miaoshu
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setGoodsMiaoshu(String goodsMiaoshu) {
        this.goodsMiaoshu = goodsMiaoshu == null ? null : goodsMiaoshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_pic
     *
     * @return the value of t_goods.goods_pic
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_pic
     *
     * @param goodsPic the value for t_goods.goods_pic
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.market_price
     *
     * @return the value of t_goods.market_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public Integer getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.market_price
     *
     * @param marketPrice the value for t_goods.market_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setMarketPrice(Integer marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.mall_price
     *
     * @return the value of t_goods.mall_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public Integer getMallPrice() {
        return mallPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.mall_price
     *
     * @param mallPrice the value for t_goods.mall_price
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setMallPrice(Integer mallPrice) {
        this.mallPrice = mallPrice;
    }

    public Catelog getCatelog() {
        return catelog;
    }

    public void setCatelog(Catelog catelog) {
        this.catelog = catelog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.stock_num
     *
     * @return the value of t_goods.stock_num
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.stock_num
     *
     * @param stockNum the value for t_goods.stock_num
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_address
     *
     * @return the value of t_goods.goods_address
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public String getGoodsAddress() {
        return goodsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_address
     *
     * @param goodsAddress the value for t_goods.goods_address
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setGoodsAddress(String goodsAddress) {
        this.goodsAddress = goodsAddress == null ? null : goodsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.enter_date
     *
     * @return the value of t_goods.enter_date
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public Date getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.enter_date
     *
     * @param enterDate the value for t_goods.enter_date
     *
     * @mbggenerated Thu Dec 19 12:00:28 CST 2019
     */
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }
}