package school.czm.entity;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.userId
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    private User user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.bankNum
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.bankPwd
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    private String bankpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.money
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    private Integer money;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "Account{" +
                "user=" + user +
                ", banknum='" + banknum + '\'' +
                ", bankpwd='" + bankpwd + '\'' +
                ", money=" + money +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.bankNum
     *
     * @return the value of t_account.bankNum
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public String getBanknum() {
        return banknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.bankNum
     *
     * @param banknum the value for t_account.bankNum
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public void setBanknum(String banknum) {
        this.banknum = banknum == null ? null : banknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.bankPwd
     *
     * @return the value of t_account.bankPwd
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public String getBankpwd() {
        return bankpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.bankPwd
     *
     * @param bankpwd the value for t_account.bankPwd
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public void setBankpwd(String bankpwd) {
        this.bankpwd = bankpwd == null ? null : bankpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.money
     *
     * @return the value of t_account.money
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.money
     *
     * @param money the value for t_account.money
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}