package school.czm.entity;

public class Orderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.orderItem_id
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    private Integer orderitemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.order_id
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    private Order order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.goods_id
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    private Good good;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderitem.goods_num
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    private Integer goodsNum;

    @Override
    public String toString() {
        return "Orderitem{" +
                "orderitemId=" + orderitemId +
                ", order=" + order +
                ", good=" + good +
                ", goodsNum=" + goodsNum +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.orderItem_id
     *
     * @return the value of t_orderitem.orderItem_id
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    public Integer getOrderitemId() {
        return orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.orderItem_id
     *
     * @param orderitemId the value for t_orderitem.orderItem_id
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    public void setOrderitemId(Integer orderitemId) {
        this.orderitemId = orderitemId;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    public Good getGood() {
        return good;
    }

    public void setGood(Good good) {
        this.good = good;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderitem.goods_num
     *
     * @return the value of t_orderitem.goods_num
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderitem.goods_num
     *
     * @param goodsNum the value for t_orderitem.goods_num
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }
}