package school.czm.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_time
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_zhuangtai
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private Integer orderZhuangtai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_jine
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private Integer orderJine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_address
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private String orderAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_pay
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private String orderPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_userid
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    private User user;

    @Override
    public String toString() {
        return "Order{" +
                "orderId='" + orderId + '\'' +
                ", orderTime=" + orderTime +
                ", orderZhuangtai=" + orderZhuangtai +
                ", orderJine=" + orderJine +
                ", orderAddress='" + orderAddress + '\'' +
                ", orderPay='" + orderPay + '\'' +
                ", user=" + user +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_time
     *
     * @return the value of t_order.order_time
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_time
     *
     * @param orderTime the value for t_order.order_time
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_zhuangtai
     *
     * @return the value of t_order.order_zhuangtai
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public Integer getOrderZhuangtai() {
        return orderZhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_zhuangtai
     *
     * @param orderZhuangtai the value for t_order.order_zhuangtai
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderZhuangtai(Integer orderZhuangtai) {
        this.orderZhuangtai = orderZhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_jine
     *
     * @return the value of t_order.order_jine
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public Integer getOrderJine() {
        return orderJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_jine
     *
     * @param orderJine the value for t_order.order_jine
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderJine(Integer orderJine) {
        this.orderJine = orderJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_address
     *
     * @return the value of t_order.order_address
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public String getOrderAddress() {
        return orderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_address
     *
     * @param orderAddress the value for t_order.order_address
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress == null ? null : orderAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_pay
     *
     * @return the value of t_order.order_pay
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public String getOrderPay() {
        return orderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_pay
     *
     * @param orderPay the value for t_order.order_pay
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setOrderPay(String orderPay) {
        this.orderPay = orderPay == null ? null : orderPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_userid
     *
     * @return the value of t_order.order_userid
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_userid
     *
     * @param user the value for t_order.order_userid
     *
     * @mbggenerated Sun Dec 15 16:29:57 CST 2019
     */
    public void setUser(User user) {
        this.user = user;
    }
}