package school.czm.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_pwd
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_realname
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_address
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_sex
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_tel
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_email
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_qq
     *
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    private String userQq;

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPwd='" + userPwd + '\'' +
                ", userRealname='" + userRealname + '\'' +
                ", userAddress='" + userAddress + '\'' +
                ", userSex='" + userSex + '\'' +
                ", userTel='" + userTel + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", userQq='" + userQq + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_pwd
     *
     * @return the value of t_user.user_pwd
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_pwd
     *
     * @param userPwd the value for t_user.user_pwd
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_realname
     *
     * @return the value of t_user.user_realname
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_realname
     *
     * @param userRealname the value for t_user.user_realname
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname == null ? null : userRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_address
     *
     * @return the value of t_user.user_address
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_address
     *
     * @param userAddress the value for t_user.user_address
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_sex
     *
     * @return the value of t_user.user_sex
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_sex
     *
     * @param userSex the value for t_user.user_sex
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_tel
     *
     * @return the value of t_user.user_tel
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_tel
     *
     * @param userTel the value for t_user.user_tel
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_email
     *
     * @return the value of t_user.user_email
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_email
     *
     * @param userEmail the value for t_user.user_email
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_qq
     *
     * @return the value of t_user.user_qq
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_qq
     *
     * @param userQq the value for t_user.user_qq
     * @mbggenerated Sun Dec 15 16:22:24 CST 2019
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq == null ? null : userQq.trim();
    }
}