package school.czm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import school.czm.entity.Account;
import school.czm.entity.User;
@Repository
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    Account selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbggenerated Wed Jan 01 16:55:48 CST 2020
     */
    int updateByPrimaryKey(Account record);

    Account selectByNumAndPwd(Account account);
}