package school.czm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.RequestParam;
import school.czm.entity.Orderitem;
@Repository
public interface OrderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    int deleteByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    int insert(Orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    Orderitem selectByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    List<Orderitem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderitem
     *
     * @mbggenerated Sun Dec 15 16:31:31 CST 2019
     */
    int updateByPrimaryKey(Orderitem record);

    List<Orderitem> getOrderItem(@Param("id") String id);
}